<a href="https://colab.research.google.com/github/BalaTechis1997/Numpy-Mini-Project/blob/main/Numpy_mini_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#Mini Project on Numpy
# Read the Data

import numpy as np
import pandas as pd
df=pd.read_csv("makeSenseOfCensus.csv")
df

age  education-num  race  ...  capital-loss  hours-per-week  income
0     39             13     4  ...             0              40       0
1     50             13     4  ...             0              13       0
2     38              9     4  ...             0              40       0
3     53              7     2  ...             0              40       0
4     28             13     2  ...             0              40       0
..   ...            ...   ...  ...           ...             ...     ...
995   56              9     4  ...             0              55       1
996   45             14     4  ...             0              45       0
997   48             13     4  ...             0              58       1
998   40             10     4  ...             0              40       0
999   39             13     4  ...             0              50       1

[1000 rows x 8 columns]

In [5]:
# Append the data

new_record=np.array([[50, 9, 4, 1, 0, 0, 40, 0]])
df=np.concatenate((df,new_record),axis=0)
df

array([[39, 13,  4, ...,  0, 40,  0],
       [50, 13,  4, ...,  0, 13,  0],
       [38,  9,  4, ...,  0, 40,  0],
       ...,
       [40, 10,  4, ...,  0, 40,  0],
       [39, 13,  4, ...,  0, 50,  1],
       [50,  9,  4, ...,  0, 40,  0]])

In [6]:
# Check if it's a young country or old country

#Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.

age=df[:,0]
age

array([39, 50, 38, ..., 40, 39, 50])

Find the max age and store it in a variable called 'max_age'.

In [7]:
max_age=age.max()
max_age

90

Find the min age and store it in a variable called 'min_age'.

In [8]:
min_age=age.min()
min_age

17

Find the mean of the age and store it in a variable called 'age_mean'.

In [9]:
mean_age=age.mean()
mean_age

38.06293706293706

Find the standard deviation of the age and store it in a variable called 'age_std'

In [10]:
std_age=np.std(age)
print(std_age)

13.341478176165857


Let's check the country's race distribution to identify the minorities

Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

In [11]:
#Array Creation:Race 0
race_0=df[df[:,2]==0]
print(race_0)

[[34  4  0  1  0  0 45  0]
 [35 10  0  0  0  0 40  0]
 [60  6  0  0  0  0 10  0]
 [51  9  0  1  0  0 40  0]
 [25 10  0  0  0  0 20  0]
 [20  9  0  1  0  0 48  0]
 [23 10  0  0  0  0 25  0]
 [29  9  0  1  0  0 40  0]
 [27 12  0  1  0  0 40  0]
 [31 12  0  0  0  0 40  0]]


In [12]:
#Array Creation:Race 1
race_1=df[df[:,2]==1]
print(race_1)

[[  30   13    1    1    0    0   40    1]
 [  40   11    1    1    0    0   40    1]
 [  54   10    1    1    0    0   60    1]
 [  30    9    1    0    0 1573   35    0]
 [  49   10    1    1    0    0   40    1]
 [  33   13    1    0    0    0   40    0]
 [  44   14    1    0    0    0   40    0]
 [  28    9    1    0    0    0   40    0]
 [  60    9    1    1    0    0   40    0]
 [  42    9    1    1    0    0   40    1]
 [  37   10    1    1    0    0   75    1]
 [  39   14    1    0 3464    0   40    0]
 [  21   10    1    0    0    0   25    0]
 [  24   10    1    0    0    0   40    0]
 [  34   14    1    1 7298    0   35    1]
 [  27   10    1    1    0 1980   40    0]
 [  40   11    1    1    0    0   40    1]
 [  55    9    1    0    0    0   40    0]
 [  35   16    1    1    0    0   40    1]
 [  29   10    1    0    0    0   40    0]
 [  20    7    1    0    0 1762   40    0]
 [  55   10    1    0    0    0   40    0]
 [  51   13    1    1    0 2415   40    1]
 [  28   11

In [13]:
#Array Creation:Race 2
race_2=df[df[:,2]==2]
print(race_2)

[[  53    7    2    1    0    0   40    0]
 [  28   13    2    0    0    0   40    0]
 [  49    5    2    0    0    0   16    0]
 [  37   10    2    1    0    0   80    1]
 [  32   12    2    1    0    0   50    0]
 [  54    9    2    0    0    0   20    0]
 [  35    5    2    1    0    0   40    0]
 [  20   10    2    1    0    0   44    0]
 [  22   10    2    1    0    0   15    0]
 [  57   13    2    1    0    0   40    1]
 [  31   13    2    0    0    0   40    0]
 [  28   10    2    0    0    0   25    0]
 [  32    9    2    1    0    0   40    0]
 [  49   11    2    1    0    0   40    1]
 [  30   13    2    1    0    0   40    0]
 [  19   10    2    1    0    0   35    0]
 [  46   12    2    0    0    0   36    0]
 [  31    9    2    0    0    0   30    0]
 [  71   10    2    1    0 1816    2    0]
 [  42   13    2    1    0    0   50    0]
 [  21    9    2    1    0    0   40    0]
 [  34    9    2    1    0    0   40    0]
 [  44   10    2    1    0    0   38    1]
 [  30   10

In [14]:
#Array Creation:Race 3
race_3=df[df[:,2]==3]
print(race_3)

[[  25   10    3    0    0    0   40    0]
 [  33   10    3    0    0    0   40    0]
 [  65    7    3    1    0    0   40    0]
 [  28    4    3    1    0 2179   40    0]
 [  44    7    3    0    0    0   46    0]
 [  40   13    3    0    0    0   55    1]]


In [15]:
#Array Creation :Race 4
race_4=df[df[:,2]==4]
print(race_4)

[[39 13  4 ...  0 40  0]
 [50 13  4 ...  0 13  0]
 [38  9  4 ...  0 40  0]
 ...
 [40 10  4 ...  0 40  0]
 [39 13  4 ...  0 50  1]
 [50  9  4 ...  0 40  0]]


In [16]:

# Storing the length of array and Storing 
#Race_0
len_0=len(race_0)
print("Length of Race_0:",len_0)

#Race_1
len_1=len(race_1)
print("Length of Race_1:",len_1)

#Race_2
len_2=len(race_2)
print("Length of Race_2:",len_2)

#Race_3
len_3=len(race_3)
print("Length of Race_3:",len_3)

#Race_4
len_4=len(race_4)
print("Length of Race_4:",len_4)

Length of Race_0: 10
Length of Race_1: 27
Length of Race_2: 110
Length of Race_3: 6
Length of Race_4: 848


In [22]:
# Minimum no of citizen 
min_citizen=min(len_0,len_1,len_2,len_3,len_4)
min_citizen

6

In [23]:
#Find out which race has minimum citizen

min_citizen=min(len_0,len_1,len_2,len_3,len_4)
if min_citizen==len_0:
  print("race_0 has minimum citizen")
elif min_citizen==len_1:
  print("race_1 has minimum citizen")
elif min_citizen==len_2:
  print("race_2 has minimum citizen")
elif min_citizen==len_3:
  print("race_3 has minimum citizen")
elif min_citizen==len_4:
  print("race_4 has minimum citizen")
else:
  print("Invalid ")

race_3 has minimum citizen


In [24]:
# Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

if min_citizen==len_0:
  minority_race=0
  print("Minority Race:",minority_race)
elif min_citizen==len_1:
  minority_race=1
  print("Minority Race:",minority_race)
elif min_citizen==len_2:
  minority_race=2
  print("Minority Race:",minority_race)
elif min_citizen==len_3:
  minority_race=3
  print("Minority Race:",minority_race)
elif min_citizen==len_4:
  minority_race=4
  print("Minority Race:",minority_race)
else:
  pass

Minority Race: 3


Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

In [25]:
#Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)
senior_citizen=df[df[:,0]>60]
print(senior_citizen)

[[   79    10     4     1     0     0    20     0]
 [   67     6     4     1     0     0     2     0]
 [   76    14     4     1     0     0    40     1]
 [   61     9     4     1     0     0    40     0]
 [   70    10     4     1     0     0    40     0]
 [   64     7     4     1     0  2179    40     0]
 [   71    10     2     1     0  1816     2     0]
 [   68     2     4     0     0     0    20     0]
 [   66    11     4     0     0     0    20     0]
 [   64     2     4     1     0     0    40     0]
 [   90     9     2     1     0  2206    40     0]
 [   66     9     4     1  1409     0    50     0]
 [   75    11     4     0     0     0    20     0]
 [   65     9     4     0     0     0    40     0]
 [   64     9     4     1     0     0    40     1]
 [   61     9     4     1     0     0    40     1]
 [   65     9     4     1     0     0    16     0]
 [   77    10     4     1     0     0    40     0]
 [   62     9     4     0     0     0    24     0]
 [   76    14     4     1     0

Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'

In [26]:

working_hours_sum=sum(senior_citizen[:,6])
print(working_hours_sum)

1917


In [29]:
# Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'
senior_citizen_len=len(senior_citizen)
print("Total no of citizen with age>60 is",senior_citizen_len)

Total no of citizen with age>60 is 61


In [30]:
#Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.
avg_working_hours=working_hours_sum/senior_citizen_len
print("Avg working hours is", avg_working_hours)

Avg working hours is 31.42622950819672


In [34]:
#checking Government policy for senior citizen 
if (avg_working_hours<25):
  print("Govt Policy is Followed")
else:
  print("Govt Policy is Not Followed")


Govt Policy is Not Followed


Let's check that higher educated people have better pay in general.

In [38]:
# Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.

high=df[df[:,1]>10]
low=df[df[:,1]<=10]

print("high: ",high)
print("low: ",low)

high:  [[39 13  4 ...  0 40  0]
 [50 13  4 ...  0 13  0]
 [28 13  2 ...  0 40  0]
 ...
 [45 14  4 ...  0 45  0]
 [48 13  4 ...  0 58  1]
 [39 13  4 ...  0 50  1]]
low:  [[38  9  4 ...  0 40  0]
 [53  7  2 ...  0 40  0]
 [49  5  2 ...  0 16  0]
 ...
 [56  9  4 ...  0 55  1]
 [40 10  4 ...  0 40  0]
 [50  9  4 ...  0 40  0]]


In [39]:
#Calculating The Avg pay for High Educated People 

sum_high=sum(high[:,7])
len_high=len(high[:,7])

avg_pay=sum_high/len_high
print("Average Pay of highly educated People is ",avg_pay)

Average Pay of highly educated People is  0.42813455657492355


In [40]:
#Calculating The Avg Pay for Low Educated People

sum_low=sum(low[:,7])
len_low=len(low[:,7])

avg_pay=sum_low/len_low
print("Average Pay of lowly educated People is ",avg_pay)


Average Pay of lowly educated People is  0.13649851632047477
